POST http://localhost:8081/brianbot/messages-upsert
Content-Type: application/json

{
    "event": "messages.upsert",
    "instance": "BrianBotTest",
    "data": {
        "key": {
            "remoteJid": "554384412362@s.whatsapp.net",
            "fromMe": true,
            "id": "3EB0450F48856304F2D44B"
        },
        "pushName": "Rodrigo Gonçalves",
        "status": "SERVER_ACK",
        "message": {
            "conversation": "/BrianBot gramatica-parametro1-parametro2-parametro3 Olá"
        },
        "messageType": "conversation",
        "messageTimestamp": 1735007705,
        "instanceId": "e21c5134-989e-47e0-89d0-4f7934f6fb9d",
        "source": "web"
    },
    "destination": "http://172.18.0.1:8080/brianbot",
    "date_time": "2024-12-23T23:35:05.858Z",
    "sender": "554384412362@s.whatsapp.net",
    "server_url": "http://localhost:8081",
    "apikey": "531C85A75A31-4A7E-8921-1938A03742CD"
}

###
POST http://localhost:8081/message/sendText/BrianBotTest
Content-Type: application/json
apikey:jxSGRK9uKS2r1AYSaLO2uxHet

{
    "number": "5543984412362",
    "text": "teste de envio"   
}