services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.0
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8081:8081
    volumes:
      - ./.data_compartilhada/instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env_evolution
    expose:
      - 8081

  redis:
    image: redis:latest
    networks:
      - evolution-net
    env_file:
      - .env_evolution
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - ./.data_compartilhada/redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    env_file:
      - .env_evolution
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.data_compartilhada/postgres:/var/lib/postgresql/data
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - evolution-net
    env_file:
      - .env_evolution
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - ./.data_compartilhada/pgadmin:/var/lib/pgadmin
    ports:
      - 4000:80
    depends_on:
      - postgres

networks:
  evolution-net:
    name: evolution-net
    driver: bridge